name: Release

on:
  workflow_call:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: '*'
          merge-multiple: true

      - name: Generate release tag
        run: echo "TAG=v$(date +'%Y%m%d%H%M%S')-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Verify artifacts
        run: |
          echo "Checking artifacts..."
          ls -R artifacts || true
          if [ ! "$(find artifacts -type f | wc -l)" -gt 0 ]; then
            echo "No artifacts found. Failing release job."
            exit 1
          fi

      - name: Create packages
        shell: bash
        run: |
          for platform_dir in artifacts/*; do
            if [ -d "$platform_dir" ] && [ "$(find "$platform_dir" -type f | wc -l)" -gt 0 ]; then
              pkg_name=$(basename "$platform_dir")
              mkdir -p "GekkoNet-$pkg_name"
              cp -r "$platform_dir/"* "GekkoNet-$pkg_name/"
              tar -czf "GekkoNet-$pkg_name-Release.tar.gz" -C "GekkoNet-$pkg_name" .
            fi
          done

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          files: GekkoNet-*-Release.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docs:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y doxygen graphviz
      - run: |
          cmake -B build -DBUILD_DOCS=ON
          cmake --build build --target docs
      - uses: actions/upload-pages-artifact@v3
        with:
          path: build/GekkoLib/docs/html
      - uses: actions/deploy-pages@v4
